spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/oath?useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

wechat:
    client:
       #appid
       clientId: wx6facec47c2fca33b
       #appSecret
       clientSecret: 65568ccf41d0e3ed967d547bf1e71166
       #code换取token链接
       accessTokenUri: https://api.weixin.qq.com/sns/oauth2/access_token
       #获取code链接
       userAuthorizationUri: https://open.weixin.qq.com/connect/oauth2/authorize
       authenticationScheme: query
       clientAuthenticationScheme: form
       #scope: snsapi_base（不弹出授权页面，直接跳转，只能获取用户openid）
       #socpe: snsapi_userinfo （弹出授权页面，可通过openid拿到昵称、性别、所在地）
       scope: snsapi_userinfo
    resource:
      #通过openid获取用户信息链接
      userInfoUri: https://api.weixin.qq.com/sns/userinfo?lang=zh_CN&openid=$OPENID$
      #获取code后 重新跳转链接    需要在链接 微信公众号网页授权域名下    (注：本地使用可以通过反向代理)
      tokenInfoUri: http://www.embracex.com/shop/login/wechat

